import numpy as np
import matplotlib.pyplot as plt
x1 = np.array([1, 1, 1, 1, 1])
x2 = np.array([1, -1, 1, -1, 1])
X1 = np.fft.fft(x1)
X2 = np.fft.fft(x2)
k = np.arange(5)
plt.figure()
plt.subplot(2, 1, 1)
plt.stem(k, np.abs(X1))
plt.xlabel("DFT index k")
plt.ylabel("|X1[k]|")
plt.title("Magnitude Response of x1[n]")
plt.grid()
plt.subplot(2, 1, 2)
plt.stem(k, np.abs(X2))
plt.xlabel("DFT index k")
plt.ylabel("|X2[k]|")
plt.title("Magnitude Response of x2[n]")
plt.grid()
plt.tight_layout()
plt.show() 
