import numpy as np
import matplotlib.pyplot as plt
Fs = 100
f0 = 5
N = 100
n = np.arange(N)
t = n / Fs
x = np.sin(2 * np.pi * f0 * t)
y = np.cos(2 * np.pi * f0 * t)
X = np.fft.fft(x)
Y = np.fft.fft(y)
X_mag = np.abs(X)
X_phase = np.angle(X)
Y_mag = np.abs(Y)
Y_phase = np.angle(Y)
X_new = X_mag * np.exp(1j * Y_phase)
Y_new = Y_mag * np.exp(1j * X_phase)
x_prime = np.real(np.fft.ifft(X_new))
y_prime = np.real(np.fft.ifft(Y_new))
plt.figure(figsize=(10, 8))
plt.subplot(4, 1, 1)
plt.plot(n, x)
plt.title("Original Signal x[n] - 5 Hz Sine Wave")
plt.xlabel("n")
plt.ylabel("Amplitude")
plt.grid()
plt.subplot(4, 1, 2)
plt.plot(n, y)
plt.title("Original Signal y[n] - 5 Hz Cosine Wave")
plt.xlabel("n")
plt.ylabel("Amplitude")
plt.grid()
plt.subplot(4, 1, 3)
plt.plot(n, x_prime)
plt.title("After Phase Interchange: x'[n]")
plt.xlabel("n")
plt.ylabel("Amplitude")
plt.grid()
plt.subplot(4, 1, 4)
plt.plot(n, y_prime)
plt.title("After Phase Interchange: y'[n]")
plt.xlabel("n")
plt.ylabel("Amplitude")
plt.grid()
plt.tight_layout()
plt.show() 